#
# Create admin accounts on opus (and possibly other login servers).
#
# Accounts are created without passwords, only SSH keys.
#

- name: Add the user mmatera
  user:
    name: mmatera
    uid: 1001
    shell: /bin/bash
    home: /home/mmatera
    groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev,docker
    append: yes

- name: Add keys for mmatera
  authorized_key:
    user: mmatera
    state: present
    key: https://github.com/mike-matera.keys
