#
# Create admin accounts on opus (and possibly other login servers).
#
# Accounts are created without passwords, only SSH keys.
#

- name: Add the user mmatera
  become: yes
  user:
    name: mmatera
    uid: 1001
    shell: /bin/bash
    home: /home/mmatera
    groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,lxd,netdev,docker
    append: yes

- name: Add keys for mmatera
  become: yes
  authorized_key:
    user: mmatera
    state: present
    key: https://github.com/mike-matera.keys

- name: Create kubernetes directory
  file:
    path: /home/mmatera/.kube
    state: directory
    owner: mmatera
    group: mmatera
    mode: '0700'

- name: Add kubernetes configuration for mmatera
  become: yes
  copy:
    src: secrets/kube-config
    dest: /home/mmatera/.kube/config 
    owner: mmatera
    group: mmatera
    mode: '600'
