---
apiVersion: v1
kind: Service
metadata:
  name: cis-dns
  labels:
    app: cis-dns
spec:
  selector:
    app: cis-dns
  ports:
    - name: dns
      port: 53
      protocol: UDP 
  externalIPs:
    - 172.30.5.250
    - 172.30.5.251
