apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-dns
  labels:
    app: cis-dns
spec:
  selector:
    matchLabels:
      app: cis-dns
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cis-dns
      annotations:
    spec:
      containers:
      - name: cis-dns
        image: mikematera/cis-dns:testing
        imagePullPolicy: Always
        env:
          - name: DNS_ROLE
            value: "external"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
