#
# Create the infrastructure kubernetes container in LXD.
#
# This assumes lxd has been setup according to the lxd role.
# Home directories will be shared with the host. 
#

- name: Create kube home directories.
  become: yes
  file:
    path: /data/homes/kube
    state: directory
    mode: '0755'

- name: Use the ubuntu user configuration from the host
  become: yes
  copy:
    src: /home/ubuntu
    dest: /data/homes/kube/
    remote_src: yes
    owner: '1000'
    group: '1000'

- name: Create kube netplan configuration directory.
  become: yes
  file:
    path: /data/config/kube/netplan
    state: directory
    mode: '0755'

- name: Create kube network configuration.
  become: yes
  blockinfile:
    create: yes
    path: /data/config/kube/netplan/99-static.yaml
    block: | 
      network:
        ethernets:
          eth0:
            addresses:
              - 172.30.5.250/24
              - 172.30.5.251/24
              - 2607:F380:80F:F425::250/64
              - 2607:F380:80F:F425::251/64
            gateway4: 172.30.5.1
            nameservers:
              search: [cis.cabrillo.edu]
              addresses: [172.30.5.101, 172.30.5.102]

# Fix for: https://github.com/corneliusweig/kubernetes-lxd/issues/10
- name: Add startup hook to increase conntrack hashsize
  become: true
  copy:
    src: files/kube-hashsize.sh
    dest: /var/lib/lxc-kube-hashsize.sh
    mode: '755'
    owner: root
    group: root

- name: Check for the kube profile.
  shell: lxc profile list | grep -q kube 
  register: kube_profile_exists 
  ignore_errors: True 
  changed_when: False 

- name: Set kube base profile.
  blockinfile:
    create: yes
    path: /tmp/kube-profile.yaml
    block: |
      name: kube
      config:
        boot.autostart: "true"
        linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter 
        raw.lxc: |
          lxc.apparmor.profile=unconfined
          lxc.mount.auto=proc:rw sys:rw cgroup:rw
          lxc.cgroup.devices.allow=a
          lxc.cap.drop=
          lxc.hook.pre-start=/var/lib/lxc-kube-hashsize.sh
        security.nesting: "true"
        security.privileged: "true"
      description: ""
      devices:
        modules:
          path: /lib/modules
          source: /lib/modules
          type: disk
        aadisable:
          path: /sys/module/nf_conntrack/parameters/hashsize
          source: /sys/module/nf_conntrack/parameters/hashsize
          type: disk
        aadisable1:
          path: /sys/module/apparmor/parameters/enabled
          source: /dev/null
          type: disk
        aadisable2:
          path: /dev/kmsg
          source: /dev/kmsg
          type: disk
    
- name: Create kube profile
  shell: 
    cmd: |
      lxc profile create kube
      lxc profile edit kube < /tmp/kube-profile.yaml
      lxc profile device add kube root disk pool=default path=/
      lxc profile device add kube homes disk source=/data/homes/kube path=/home
      lxc profile device add kube netplan disk source=/data/config/kube/netplan path=/etc/netplan
      lxc profile device add kube eth0 nic name=eth0 nictype=bridged parent=server
  when: kube_profile_exists.rc == 1 

- name: Check if kube exists.
  shell: lxc list | grep -q kube 
  register: kube_exists 
  ignore_errors: True 
  changed_when: False 

- name: Create kube 
  shell:
    cmd: | 
      lxc launch ubuntu:18.04 kube -p kube 
  when: kube_exists.rc == 1
