---
# 
# Playbook for the Dell R620-1 Machine
#
# This machine is deployed by MAAS and hosts the jupyter container. 
#

- hosts: dell-r620-1
  name: Apply networking configuration
  roles:
    - netplan 

- hosts: dell-r620-1
  name: Apply disk layout to R620 hosts and setup LXD
  roles:
    - lvm-r620
    - lxd

- hosts: dell-r620-1
  name: Setup dell-r620-1 as a kube server
  vars: 
    kube_hostname: kube2
    external_address_list: 
      - 172.30.5.253/24 
      - 172.30.5.102/24
      - 2607:F380:80F:F425::253/64
      - 2607:F380:80F:F425::102/64
    external_mac_addr: 00:16:3e:1f:36:a3
  tags:
    - kube
  roles:
    - kube

