---
# 
# Playbook for the Dell R620-1 Machine
#
# This machine is deployed by MAAS and hosts opus and kube. 
#

- hosts: dell-r620-2
  name: Apply networking configuration
  roles:
    - netplan 

- hosts: dell-r620-2
  name: Apply disk layout to R620 hosts
  roles:
    - lvm-r620

- hosts: dell-r620-2
  name: Setup dell-r620-2 to serve critical infrastructure.
  tags:
    - opus
    - kube
  roles:
    - lxd
    - opus
    - kube
