#
# Deploy jupyterhub 
#
- name: Install JupyterHub on jupyter.cis.cabrillo.edu
  hosts: jupyter
  tags:
    - jupyter
  become: true
  roles:
    - admins
  tasks: 
    - name: Add caddy repository. 
      apt_repository:
        repo: deb [trusted=yes] https://apt.fury.io/caddy/ / 
        state: present
        filename: caddy

    - name: Install caddy
      apt:
        update-cache: yes
        pkg:
        - caddy

    - name: Configure caddy 
      copy:
        content: |
          jupyter.cis.cabrillo.edu

          reverse_proxy 127.0.0.1:8000
        dest: /etc/caddy/Caddyfile

    - name: Reload caddy
      service:
        name: caddy
        state: reloaded

    - name: Install packages. 
      apt:
        update_cache: yes
        pkg:
          - python3-pip
          - python3-venv
          - npm
          - nginx

    - name: Remove old node package. 
      apt:
        pkg:
          - nodejs
        state: absent

    - name: Install newer node by snap
      snap:
        name: node
        channel: 14/stable
        classic: yes


- name: Install and configure the Python environment.
  hosts: jupyter
  tags:
    - jupyter-venv
  tasks: 

    - name: Create the virtualenv directory
      become: yes
      file:
        path: /opt/jupyterhub
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
  
    - name: Install Python wheel. 
      pip:
        virtualenv: /opt/jupyterhub
        virtualenv_command: /usr/bin/python3 -m venv
        name:
          - wheel 

    - name: Install JupyterHub.
      pip:
        virtualenv: /opt/jupyterhub
        virtualenv_command: /usr/bin/python3 -m venv
        name:
          - jupyterhub 
          - jupyterlab 

    - name: Install JS components.
      become: yes
      npm:
        name: configurable-http-proxy
        global: yes

    - name: Create the JupyterHub configuration
      file:
        path: /opt/jupyterhub/etc/jupyterhub
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create default JupyterHub configuration 
      shell: /opt/jupyterhub/bin/jupyterhub --generate-config 
      args:
        chdir: /opt/jupyterhub/etc/jupyterhub
        creates: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py        

    - name: Set JupyterLab to the default interface
      lineinfile:
        path: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
        regexp: 'c.Spawner.default_url'
        line: c.Spawner.default_url = '/lab' 

    - name: Set JupyterLab URL
      lineinfile:
        path: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
        regexp: 'c.JupyterHub.bind_url'
        line: c.JupyterHub.bind_url = 'http://localhost:8000/'

    - name: Create the JupyterHub service 
      become: yes
      file:
        path: /opt/jupyterhub/etc/systemd
        state: directory
        owner: root
        group: ubuntu
        mode: '0775'

    - name: Write JupyterHub serivce file. 
      become: yes
      blockinfile:
        owner: root
        group: ubuntu
        path: /opt/jupyterhub/etc/systemd/jupyterhub.service
        create: yes
        block: |
          [Unit]
          Description=JupyterHub
          After=syslog.target network.target

          [Service]
          User=root
          Environment="PATH=/opt/jupyterhub/bin:/snap/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
          ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

          [Install]
          WantedBy=multi-user.target

    - name: Install JupyterHub service. 
      become: yes
      file: 
        src: /opt/jupyterhub/etc/systemd/jupyterhub.service 
        dest: /etc/systemd/system/jupyterhub.service
        owner: root
        group: root
        state: link

    - name: Reload systemd config
      become: yes
      systemd:
        daemon_reload: yes

    - name: Enable and start JupyterHub
      become: yes
      systemd:
        name: jupyterhub
        enabled: yes
        state: started

    - name: Allow HTTP
      become: yes
      ufw:
        rule: allow
        port: '80'
        proto: tcp
            
    - name: Allow HTTPs
      become: yes
      ufw:
        rule: allow
        port: '443'
        proto: tcp

