    
- hosts: all
  vars:
    primary_interface: enp0s8
    ssd_physical: /dev/sdc 
    disk_physical: /dev/sdd
    vg_disk_pool_size: 64 
    vg_disk_home_size: 32

  name: Test configuration
  roles:
    - netplan 
    - lvm-vagrant
    - lxd
    - opus
    - kube
